version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'monday'
      time: '09:00'
      timezone: 'Etc/UTC'
    open-pull-requests-limit: 1
    assignees:
      - 'TheOluwafemi'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
    groups:
      production-dependencies:
        patterns:
          - 'axios'
      development-dependencies:
        patterns:
          - '@types/*'
          - '@semantic-release/*'
          - '@typescript-eslint/*'
          - 'eslint*'
          - 'jest*'
          - 'ts-*'
          - 'typescript'
          - 'tsup'
